### ISSUE TITLE
显示不出来标注

### ISSUE THREAD

**Issue by tanst** [m544498510/ChengduGouFanApp#1]
开始提示百度地图的AK错误，后来在index.html换成我自己的，也显示不出来了
----
获取不了房协数据

**Comment by m544498510** [comment]
> ## 开始提示百度地图的AK错误，后来在index.html换成我自己的，也显示不出来了
> 获取不了房协数据

是百度地图出不来，还是没有显示位置的Mark。如果是没有房子位置的Mark，是百度api返回值结构变化导致的，已经修改新的解析方式。

**Comment by tanst** [comment]
谢谢，已经摇到号了
